#!/bin/bash
apt update
sleep 1
apt install gcc g++ make libxt-dev libx11-dev nam xorg-dev libxmu-dev libperl4-corelibs-perl -y
sleep 1
cd ./ns-allinone-2.35/
./install
sleep 2
source ~/.bashrc
echo "Done! Try \"ns\" command and see if it showed \"%\""

exit 0
