#!/bin/bash
apt update
sleep 1
apt install gcc g++ make libxt-dev libx11-dev nam -y
sleep 1
cd ./ns-allinone-2.35/
./install
sleep 1
source ~/.bashrc
sleep 1
echo "Done! Try \"ns\" command and see if it showed \"%\""

exit 0
